import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { handler } from '../../../mcp/tools/renderPlan.js';

describe('renderPlan tool', () => {
  let tmpDir: string;
  let missionPath: string;
  let planPath: string;

  beforeAll(() => {
    tmpDir = fs.mkdtempSync('/tmp/concert-render-plan-');
    missionPath = path.join(tmpDir, '.concert', 'missions', 'test');
    const p1 = path.join(missionPath, 'phases', '01-phase');
    const p2 = path.join(missionPath, 'phases', '02-phase');
    fs.mkdirSync(p1, { recursive: true });
    fs.mkdirSync(p2, { recursive: true });
    fs.writeFileSync(path.join(tmpDir, 'state.json'), JSON.stringify({ mission: 'test' }));

    planPath = path.join(missionPath, 'PLAN.md');
    fs.writeFileSync(
      planPath,
      `# Plan

<!-- CONCERT:PLAN-TABLES:START — auto-generated by \`concert render-plan\`. Do not edit between markers. -->
<!-- CONCERT:PLAN-TABLES:END -->

More content here.`
    );

    fs.writeFileSync(
      path.join(p1, 'TASK-a.md'),
      `---
task: a
title: Task A
wave: 0
model: haiku
depends_on: []
---

## Acceptance Criteria

- [x] Done`
    );

    fs.writeFileSync(
      path.join(p2, 'TASK-b.md'),
      `---
task: b
title: Task B
wave: 1
depends_on: ['a']
---

## Acceptance Criteria

- [ ] Pending`
    );
  });

  afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('renders plan tables and preserves content outside markers', async () => {
    process.env.CONCERT_CACHE_DISABLED = '1';
    const result = await handler({ mission: 'test' }, { cwd: tmpDir });
    expect(result.ok).toBe(true);
    expect(result.tasksRendered).toBe(2);
    expect(result.phasesRendered).toBe(2);

    const content = fs.readFileSync(planPath, 'utf-8');
    expect(content).toContain('# Plan');
    expect(content).toContain('More content here.');
    expect(content).toContain('### Phase 01-phase');
    expect(content).toContain('### Phase 02-phase');
    expect(content).toContain('| a | haiku | 0 | - | done |');
    expect(content).toContain('| b | - | 1 | a | pending |');
  });

  it('fails if PLAN.md missing', async () => {
    process.env.CONCERT_CACHE_DISABLED = '1';
    const emptyDir = fs.mkdtempSync('/tmp/concert-no-plan-');
    const emptyMission = path.join(emptyDir, '.concert', 'missions', 'empty');
    fs.mkdirSync(emptyMission, { recursive: true });
    fs.writeFileSync(path.join(emptyDir, 'state.json'), JSON.stringify({ mission: 'empty' }));

    try {
      const result = await handler({ mission: 'empty' }, { cwd: emptyDir });
      expect(result.ok).toBe(false);
      expect(result.error).toContain('PLAN.md not found');
    } finally {
      fs.rmSync(emptyDir, { recursive: true, force: true });
    }
  });

  it('fails if markers missing', async () => {
    const badPath = path.join(missionPath, 'PLAN.md');
    fs.writeFileSync(badPath, '# Plan without markers');

    process.env.CONCERT_CACHE_DISABLED = '1';
    const result = await handler({ mission: 'test' }, { cwd: tmpDir });
    expect(result.ok).toBe(false);
    expect(result.error).toContain('missing CONCERT:PLAN-TABLES markers');
  });

  it('renders empty block for mission with no tasks', async () => {
    const emptyMission = path.join(tmpDir, '.concert', 'missions', 'empty');
    fs.mkdirSync(emptyMission, { recursive: true });
    const emptyPlanPath = path.join(emptyMission, 'PLAN.md');
    fs.writeFileSync(
      emptyPlanPath,
      `# Empty\n\n<!-- CONCERT:PLAN-TABLES:START — auto-generated by \`concert render-plan\`. Do not edit between markers. -->\n<!-- CONCERT:PLAN-TABLES:END -->`
    );

    process.env.CONCERT_CACHE_DISABLED = '1';
    const result = await handler({ mission: 'empty' }, { cwd: tmpDir });
    expect(result.ok).toBe(true);
    expect(result.tasksRendered).toBe(0);
    expect(result.phasesRendered).toBe(0);
  });
});
