import * as fs from 'node:fs';
import * as path from 'node:path';
import { isManagedFile, extractHeaderVersion, stampVersion } from './version.js';

export interface CopyResult {
  created: string[];
  skipped: string[];
  overwritten: string[];
}

export interface CleanupResult {
  deleted: string[];
}

/**
 * Copy a file, stamping the current version into any managed header.
 * If the file has an "AUTO-GENERATED BY CONCERT vX.Y.Z" header,
 * the version is replaced with the target version.
 * If no managed header is found, the file is copied as-is.
 */
function copyFileWithVersionStamp(srcFile: string, destFile: string, version: string): void {
  const content = fs.readFileSync(srcFile, 'utf-8');
  const stamped = stampVersion(content, version);
  fs.writeFileSync(destFile, stamped);
}

/**
 * Resolve the package root directory (parent of dist/).
 */
export function resolvePackageRoot(): string {
  // __dirname points to dist/ when bundled
  const fromDist = path.resolve(__dirname, '..');
  if (fs.existsSync(path.join(fromDist, 'templates'))) {
    return fromDist;
  }
  // Development: use cwd
  const fromCwd = process.cwd();
  if (fs.existsSync(path.join(fromCwd, 'templates'))) {
    return fromCwd;
  }
  throw new Error('Cannot find package root directory');
}

/**
 * Copy all files from source directory to target directory recursively.
 *
 * @param srcDir - Source directory (templates/)
 * @param targetDir - Target directory (user's project root)
 * @param overwrite - Whether to overwrite existing files
 * @param version - If provided, stamp managed headers with this version
 * @returns Summary of files created, skipped, and overwritten
 */
export function copyTemplates(
  srcDir: string,
  targetDir: string,
  overwrite: boolean = false,
  version?: string
): CopyResult {
  const result: CopyResult = { created: [], skipped: [], overwritten: [] };
  copyRecursive(srcDir, targetDir, '', overwrite, result, version);
  return result;
}

function copyRecursive(
  srcDir: string,
  targetDir: string,
  relativePath: string,
  overwrite: boolean,
  result: CopyResult,
  version?: string
): void {
  const srcPath = path.join(srcDir, relativePath);
  const entries = fs.readdirSync(srcPath, { withFileTypes: true });

  for (const entry of entries) {
    const relPath = relativePath ? path.join(relativePath, entry.name) : entry.name;
    const srcFile = path.join(srcDir, relPath);
    const targetFile = path.join(targetDir, relPath);

    if (entry.isDirectory()) {
      if (!fs.existsSync(targetFile)) {
        fs.mkdirSync(targetFile, { recursive: true });
      }
      copyRecursive(srcDir, targetDir, relPath, overwrite, result, version);
    } else {
      if (fs.existsSync(targetFile)) {
        if (overwrite) {
          if (version) {
            copyFileWithVersionStamp(srcFile, targetFile, version);
          } else {
            fs.copyFileSync(srcFile, targetFile);
          }
          result.overwritten.push(relPath);
        } else {
          result.skipped.push(relPath);
        }
      } else {
        const dir = path.dirname(targetFile);
        if (!fs.existsSync(dir)) {
          fs.mkdirSync(dir, { recursive: true });
        }
        if (version) {
          copyFileWithVersionStamp(srcFile, targetFile, version);
        } else {
          fs.copyFileSync(srcFile, targetFile);
        }
        result.created.push(relPath);
      }
    }
  }
}

/**
 * Rules that are specific to the Concert source repo and should NOT
 * be deployed to target repos.
 */
export const EXCLUDED_RULES = ['concert-repo-managed-files.md', 'concert-managed-file-headers.md'];

/**
 * Live file sources that ship directly from the package (not templates).
 * Each entry maps a source directory (relative to package root) to a target
 * directory (relative to user's project root), with a filename pattern filter
 * and an optional exclusion list for files that should not be shipped.
 */
export const LIVE_FILE_SOURCES = [
  { src: '.github/agents', target: '.github/agents', pattern: /^concert-.*\.agent\.md$/ },
  { src: '.claude/commands', target: '.claude/commands', pattern: /^concert-.*\.md$/ },
  {
    src: '.claude/rules',
    target: '.claude/rules',
    pattern: /^concert-.*\.md$/,
    exclude: EXCLUDED_RULES,
  },
] as const;

/**
 * Copy live files from the package root to the target directory.
 * Only copies files matching LIVE_FILE_SOURCES patterns.
 * When version is provided, stamps the current version into managed file headers.
 */
export function copyLiveFiles(
  packageRoot: string,
  targetDir: string,
  overwrite: boolean,
  version?: string
): CopyResult {
  const result: CopyResult = { created: [], skipped: [], overwritten: [] };

  for (const source of LIVE_FILE_SOURCES) {
    const srcDir = path.join(packageRoot, source.src);
    if (!fs.existsSync(srcDir)) continue;

    const targetPath = path.join(targetDir, source.target);
    if (!fs.existsSync(targetPath)) {
      fs.mkdirSync(targetPath, { recursive: true });
    }

    const entries = fs.readdirSync(srcDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isFile()) continue;
      if (!source.pattern.test(entry.name)) continue;
      if ('exclude' in source && source.exclude.includes(entry.name)) continue;

      const srcFile = path.join(srcDir, entry.name);
      const destFile = path.join(targetPath, entry.name);
      const relPath = path.join(source.target, entry.name);

      if (fs.existsSync(destFile)) {
        if (overwrite) {
          if (version) {
            copyFileWithVersionStamp(srcFile, destFile, version);
          } else {
            fs.copyFileSync(srcFile, destFile);
          }
          result.overwritten.push(relPath);
        } else {
          result.skipped.push(relPath);
        }
      } else {
        if (version) {
          copyFileWithVersionStamp(srcFile, destFile, version);
        } else {
          fs.copyFileSync(srcFile, destFile);
        }
        result.created.push(relPath);
      }
    }
  }

  return result;
}

/**
 * Count live files that would be installed from the package.
 */
export function countLiveFiles(packageRoot: string): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const source of LIVE_FILE_SOURCES) {
    const srcDir = path.join(packageRoot, source.src);
    if (!fs.existsSync(srcDir)) continue;
    const category = path.basename(source.src);
    const entries = fs.readdirSync(srcDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isFile()) continue;
      if (!source.pattern.test(entry.name)) continue;
      if ('exclude' in source && source.exclude.includes(entry.name)) continue;
      counts[category] = (counts[category] ?? 0) + 1;
    }
  }
  return counts;
}

/**
 * Clean up stale Concert-managed files in a target directory.
 *
 * Scans known directories for files that have the managed header
 * ("AUTO-GENERATED BY CONCERT") but whose version does NOT match
 * the current version. These are leftover files from a previous
 * Concert version that are no longer shipped.
 *
 * Files that don't have a managed header at all are left untouched —
 * they are user-created files.
 *
 * @param targetDir - The user's project root directory
 * @param currentVersion - The current Concert package version
 * @returns List of deleted file paths (relative to targetDir)
 */
export function cleanupStaleFiles(targetDir: string, currentVersion: string): CleanupResult {
  const result: CleanupResult = { deleted: [] };

  // Directories to scan for stale Concert-managed files.
  // These match the LIVE_FILE_SOURCES patterns.
  const scanDirs: Array<{ dir: string; pattern: RegExp; exclude?: readonly string[] }> = [
    { dir: '.github/agents', pattern: /^concert-.*\.agent\.md$/ },
    { dir: '.claude/commands', pattern: /^concert-.*\.md$/ },
    { dir: '.claude/rules', pattern: /^concert-.*\.md$/, exclude: EXCLUDED_RULES },
  ];

  for (const { dir, pattern, exclude } of scanDirs) {
    const fullDir = path.join(targetDir, dir);
    if (!fs.existsSync(fullDir)) continue;
    const entries = fs.readdirSync(fullDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isFile()) continue;
      if (!pattern.test(entry.name)) continue;
      if (exclude?.includes(entry.name)) continue;
      const filePath = path.join(fullDir, entry.name);
      const content = fs.readFileSync(filePath, 'utf-8');
      if (!isManagedFile(content)) continue;
      const fileVersion = extractHeaderVersion(content);
      // Delete if managed but version doesn't match current
      if (fileVersion !== null && fileVersion !== currentVersion) {
        fs.unlinkSync(filePath);
        result.deleted.push(path.join(dir, entry.name));
      }
    }
  }

  return result;
}
