import * as fs from 'node:fs';
import * as path from 'node:path';
import { listMissions } from '../../lib/missions.js';
import { readState } from '../../lib/state.js';
import { withCache } from '../../cache/cache.js';
import { parseTaskFrontmatter } from '../../lib/task-frontmatter.js';
import { parseAcceptance } from '../../lib/section-edit.js';
import { deriveTaskStatus as deriveStatus } from '../../lib/task-status.js';
import { atomicWriteFile } from '../../lib/atomic-write.js';
import { withMissionLock } from '../../lib/file-lock.js';
import { appendEventSafe } from '../../cache/cache.js';
import { renderPlanInputSchema, renderPlanOutputSchema } from '../schemas.js';
import type { ToolDefinition, ToolContext } from '../registry.js';

export const name = 'concert.render_plan';
export const description = 'Render per-phase task tables into PLAN.md';
export const inputSchema = renderPlanInputSchema;
export const outputSchema = renderPlanOutputSchema;

interface RenderPlanInput {
  mission?: string;
}

interface RenderPlanOutput {
  ok: boolean;
  missionPlanPath?: string;
  tasksRendered?: number;
  phasesRendered?: number;
  error?: string;
}

interface TaskRow {
  task: string;
  title: string;
  phase: string | null;
  wave: number;
  model: string | null;
  dependsOn: string[];
  status: 'pending' | 'in-progress' | 'done';
}

export const handler: ToolDefinition<RenderPlanInput, RenderPlanOutput>['handler'] = async (
  args,
  ctx
) => {
  const missionSlug = args.mission ?? readState(ctx.cwd)?.mission ?? null;
  if (!missionSlug) {
    throw new Error('No active mission; specify --mission or set one via state.json');
  }

  const missions = listMissions(ctx.cwd);
  const mission = missions.find((m) => m.slug === missionSlug);
  if (!mission) {
    throw new Error(`Mission not found: ${missionSlug}`);
  }

  const planPath = path.join(mission.path, 'PLAN.md');
  if (!fs.existsSync(planPath)) {
    return {
      ok: false,
      error: 'PLAN.md not found',
    };
  }

  const tasks = await withCache<TaskRow[]>(
    ctx.cwd,
    async (handle) => {
      const db = handle.db as {
        prepare(sql: string): {
          all(...args: unknown[]): unknown[];
        };
      };

      type DBRow = {
        task_slug: string;
        title: string;
        phase: string | null;
        wave: number;
        model: string | null;
        depends_on: string;
        total_acceptance: number;
        completed_acceptance: number;
      };

      const rows = db
        .prepare(
          'SELECT task_slug, title, phase, wave, model, depends_on, total_acceptance, completed_acceptance FROM tasks WHERE mission_slug = ? ORDER BY phase, wave, task_slug'
        )
        .all(missionSlug) as DBRow[];

      return rows.map((r) => ({
        task: r.task_slug,
        title: r.title,
        phase: r.phase,
        wave: r.wave,
        model: r.model,
        dependsOn: JSON.parse(r.depends_on) as string[],
        status: deriveStatus(r.total_acceptance, r.completed_acceptance),
      }));
    },
    async () => {
      return await readTasksFromDisk(mission.path);
    }
  );

  const grouped = new Map<string, TaskRow[]>();
  for (const task of tasks) {
    const phase = task.phase ?? 'unknown';
    if (!grouped.has(phase)) {
      grouped.set(phase, []);
    }
    grouped.get(phase)!.push(task);
  }

  const sortedPhases = Array.from(grouped.keys()).sort();
  let tableBlock =
    '<!-- CONCERT:PLAN-TABLES:START — auto-generated by `concert render-plan`. Do not edit between markers. -->\n\n';

  for (const phase of sortedPhases) {
    const phaseTasks = grouped.get(phase)!;
    tableBlock += `### Phase ${phase}\n`;
    tableBlock += '| Task | Model | Wave | Depends On | Status |\n';
    tableBlock += '| ---- | ----- | ---- | ---------- | ------ |\n';
    for (const t of phaseTasks) {
      const model = t.model ?? '-';
      const dependsOn = t.dependsOn.length > 0 ? t.dependsOn.join(', ') : '-';
      const status = t.status;
      tableBlock += `| ${t.task} | ${model} | ${t.wave} | ${dependsOn} | ${status} |\n`;
    }
    tableBlock += '\n';
  }

  tableBlock += '<!-- CONCERT:PLAN-TABLES:END -->';

  const planContent = fs.readFileSync(planPath, 'utf-8');
  const startMarker = '<!-- CONCERT:PLAN-TABLES:START';
  const endMarker = '<!-- CONCERT:PLAN-TABLES:END -->';

  const startIdx = planContent.indexOf(startMarker);
  const endIdx = planContent.indexOf(endMarker);

  if (startIdx === -1 || endIdx === -1) {
    return {
      ok: false,
      error:
        'PLAN.md missing CONCERT:PLAN-TABLES markers — add the START/END comment pair where you want the tables rendered, then re-run',
    };
  }

  const before = planContent.slice(0, startIdx);
  const after = planContent.slice(endIdx + endMarker.length);
  const updated = before + tableBlock + after;

  let result: RenderPlanOutput;

  await withMissionLock(mission.path, async () => {
    atomicWriteFile(planPath, updated);

    await appendEventSafe(ctx.cwd, {
      ts: new Date().toISOString(),
      mission_slug: missionSlug,
      tool: 'concert.render_plan',
      args_hash: JSON.stringify(args),
      doc: 'PLAN.md',
      section: null,
      ok: true,
      error_class: null,
      duration_ms: 0,
    });

    result = {
      ok: true,
      missionPlanPath: path.relative(ctx.cwd, planPath),
      tasksRendered: tasks.length,
      phasesRendered: sortedPhases.length,
    };
  });

  return result!;
};

async function readTasksFromDisk(missionPath: string): Promise<TaskRow[]> {
  const tasks: TaskRow[] = [];
  const phasesDir = path.join(missionPath, 'phases');
  if (!fs.existsSync(phasesDir)) return tasks;

  const phaseEntries = fs.readdirSync(phasesDir, { withFileTypes: true });
  for (const phaseEntry of phaseEntries) {
    if (!phaseEntry.isDirectory()) continue;
    const phasePath = path.join(phasesDir, phaseEntry.name);
    const taskFiles = fs
      .readdirSync(phasePath, { withFileTypes: true })
      .filter((e) => e.isFile() && /^TASK-.*\.md$/.test(e.name));

    for (const taskFile of taskFiles) {
      const taskFilePath = path.join(phasePath, taskFile.name);
      try {
        const content = fs.readFileSync(taskFilePath, 'utf-8');
        const parsed = parseTaskFrontmatter(content);
        if (!parsed.frontmatter) continue;

        const fm = parsed.frontmatter;
        const acceptance = parseAcceptance(content);
        const totalAcceptance = acceptance.length;
        const completedAcceptance = acceptance.filter((a) => a.done).length;

        tasks.push({
          task: fm.task,
          title: fm.title,
          phase: fm.phase ?? phaseEntry.name,
          wave: fm.wave,
          model: fm.model ?? null,
          dependsOn: fm.depends_on,
          status: deriveStatus(totalAcceptance, completedAcceptance),
        });
      } catch {
        // Skip malformed files
      }
    }
  }

  return tasks;
}
