import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import {
  copyTemplates,
  copyManagedFiles,
  countTemplateFiles,
  cleanupStaleFiles,
} from '../lib/copy.js';

let tmpSrc: string;
let tmpTarget: string;

beforeEach(() => {
  tmpSrc = fs.mkdtempSync(path.join(os.tmpdir(), 'concert-copy-src-'));
  tmpTarget = fs.mkdtempSync(path.join(os.tmpdir(), 'concert-copy-target-'));
  // Create some test files in src
  fs.mkdirSync(path.join(tmpSrc, 'subdir'), { recursive: true });
  fs.writeFileSync(path.join(tmpSrc, 'file1.txt'), 'content 1');
  fs.writeFileSync(path.join(tmpSrc, 'file2.txt'), 'content 2');
  fs.writeFileSync(path.join(tmpSrc, 'subdir', 'file3.txt'), 'content 3');
});

afterEach(() => {
  fs.rmSync(tmpSrc, { recursive: true, force: true });
  fs.rmSync(tmpTarget, { recursive: true, force: true });
});

describe('copyTemplates', () => {
  it('copies all files from source to empty target', () => {
    const result = copyTemplates(tmpSrc, tmpTarget);
    expect(result.created).toHaveLength(3);
    expect(result.skipped).toHaveLength(0);
    expect(result.overwritten).toHaveLength(0);
    expect(fs.existsSync(path.join(tmpTarget, 'file1.txt'))).toBe(true);
    expect(fs.existsSync(path.join(tmpTarget, 'file2.txt'))).toBe(true);
    expect(fs.existsSync(path.join(tmpTarget, 'subdir', 'file3.txt'))).toBe(true);
  });

  it('skips existing files when overwrite is false', () => {
    // Pre-create one file
    fs.writeFileSync(path.join(tmpTarget, 'file1.txt'), 'existing content');
    const result = copyTemplates(tmpSrc, tmpTarget, false);
    expect(result.created).toHaveLength(2);
    expect(result.skipped).toHaveLength(1);
    expect(result.overwritten).toHaveLength(0);
    // Original content should remain
    expect(fs.readFileSync(path.join(tmpTarget, 'file1.txt'), 'utf-8')).toBe('existing content');
  });

  it('overwrites existing files when overwrite is true', () => {
    fs.writeFileSync(path.join(tmpTarget, 'file1.txt'), 'old content');
    const result = copyTemplates(tmpSrc, tmpTarget, true);
    expect(result.overwritten).toHaveLength(1);
    expect(fs.readFileSync(path.join(tmpTarget, 'file1.txt'), 'utf-8')).toBe('content 1');
  });

  it('creates nested directories', () => {
    const result = copyTemplates(tmpSrc, tmpTarget);
    expect(fs.existsSync(path.join(tmpTarget, 'subdir'))).toBe(true);
    expect(result.created.some((f) => f.includes('file3'))).toBe(true);
  });
});

describe('copyManagedFiles', () => {
  it('only overwrites files with managed headers', () => {
    const managedContent =
      '<!-- AUTO-GENERATED BY CONCERT v0.1.0 — DO NOT EDIT. -->\nmanaged content';
    const userContent = '# User file\nuser content';
    fs.writeFileSync(path.join(tmpSrc, 'managed.md'), managedContent);
    fs.writeFileSync(
      path.join(tmpSrc, 'user.md'),
      '<!-- AUTO-GENERATED BY CONCERT v0.1.0 — DO NOT EDIT. -->\nnew content'
    );
    // Pre-create target files
    fs.writeFileSync(path.join(tmpTarget, 'managed.md'), managedContent);
    fs.writeFileSync(path.join(tmpTarget, 'user.md'), userContent);
    const result = copyManagedFiles(tmpSrc, tmpTarget);
    // managed.md should be overwritten (it has managed header in target)
    expect(result.overwritten.some((f) => f.includes('managed.md'))).toBe(true);
    // user.md should NOT be overwritten (no managed header in target)
    expect(result.skipped.some((f) => f.includes('user.md'))).toBe(true);
    // user.md content should remain unchanged
    expect(fs.readFileSync(path.join(tmpTarget, 'user.md'), 'utf-8')).toBe(userContent);
  });

  it('skips files without managed headers', () => {
    fs.writeFileSync(path.join(tmpSrc, 'normal.txt'), 'new content');
    fs.writeFileSync(path.join(tmpTarget, 'normal.txt'), 'original');
    const result = copyManagedFiles(tmpSrc, tmpTarget);
    expect(result.skipped).toContain('normal.txt');
    expect(fs.readFileSync(path.join(tmpTarget, 'normal.txt'), 'utf-8')).toBe('original');
  });

  it("creates new files that don't exist in target", () => {
    fs.writeFileSync(path.join(tmpSrc, 'new-file.md'), 'new content');
    const result = copyManagedFiles(tmpSrc, tmpTarget);
    expect(result.created.some((f) => f.includes('new-file.md'))).toBe(true);
    expect(fs.existsSync(path.join(tmpTarget, 'new-file.md'))).toBe(true);
  });
});

describe('countTemplateFiles', () => {
  it('correctly counts files by category', () => {
    fs.mkdirSync(path.join(tmpSrc, 'agents'), { recursive: true });
    fs.mkdirSync(path.join(tmpSrc, 'workflows'), { recursive: true });
    fs.writeFileSync(path.join(tmpSrc, 'agents', 'agent1.md'), 'agent 1');
    fs.writeFileSync(path.join(tmpSrc, 'agents', 'agent2.md'), 'agent 2');
    fs.writeFileSync(path.join(tmpSrc, 'workflows', 'wf1.md'), 'workflow 1');
    const counts = countTemplateFiles(tmpSrc);
    expect(counts['agents']).toBe(2);
    expect(counts['workflows']).toBe(1);
  });

  it('excludes .gitkeep files from counts', () => {
    fs.mkdirSync(path.join(tmpSrc, 'missions'), { recursive: true });
    fs.writeFileSync(path.join(tmpSrc, 'missions', '.gitkeep'), '');
    const counts = countTemplateFiles(tmpSrc);
    expect(counts['missions']).toBeUndefined();
  });
});

describe('cleanupStaleFiles', () => {
  let cleanupDir: string;

  beforeEach(() => {
    cleanupDir = fs.mkdtempSync(path.join(os.tmpdir(), 'concert-cleanup-'));
  });

  afterEach(() => {
    fs.rmSync(cleanupDir, { recursive: true, force: true });
  });

  it('deletes agent files with old version', () => {
    const agentsDir = path.join(cleanupDir, '.claude', 'agents');
    fs.mkdirSync(agentsDir, { recursive: true });
    fs.writeFileSync(
      path.join(agentsDir, 'concert-old-agent.md'),
      '---\nname: concert-old-agent\n---\n\n<!-- AUTO-GENERATED BY CONCERT v0.5.0 — DO NOT EDIT. -->\nold content'
    );
    fs.writeFileSync(
      path.join(agentsDir, 'concert-current.md'),
      '---\nname: concert-current\n---\n\n<!-- AUTO-GENERATED BY CONCERT v2.0.0 — DO NOT EDIT. -->\ncurrent content'
    );
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toContain(path.join('.claude', 'agents', 'concert-old-agent.md'));
    expect(result.deleted).not.toContain(path.join('.claude', 'agents', 'concert-current.md'));
    expect(fs.existsSync(path.join(agentsDir, 'concert-old-agent.md'))).toBe(false);
    expect(fs.existsSync(path.join(agentsDir, 'concert-current.md'))).toBe(true);
  });

  it('leaves non-concert agent files untouched', () => {
    const agentsDir = path.join(cleanupDir, '.claude', 'agents');
    fs.mkdirSync(agentsDir, { recursive: true });
    fs.writeFileSync(path.join(agentsDir, 'my-custom-agent.md'), '# My custom agent');
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toHaveLength(0);
    expect(fs.existsSync(path.join(agentsDir, 'my-custom-agent.md'))).toBe(true);
  });

  it('leaves files without managed header untouched', () => {
    const agentsDir = path.join(cleanupDir, '.claude', 'agents');
    fs.mkdirSync(agentsDir, { recursive: true });
    fs.writeFileSync(
      path.join(agentsDir, 'concert-user-agent.md'),
      '---\nname: concert-user-agent\n---\n# User-created agent with concert- prefix'
    );
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toHaveLength(0);
    expect(fs.existsSync(path.join(agentsDir, 'concert-user-agent.md'))).toBe(true);
  });

  it('deletes stale workflow files', () => {
    const wfDir = path.join(cleanupDir, '.concert', 'workflows');
    fs.mkdirSync(wfDir, { recursive: true });
    fs.writeFileSync(
      path.join(wfDir, 'CONCERT-WORKFLOW-OLD.md'),
      '<!-- AUTO-GENERATED BY CONCERT v0.1.0 — DO NOT EDIT -->\nold workflow'
    );
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toContain(path.join('.concert', 'workflows', 'CONCERT-WORKFLOW-OLD.md'));
    expect(fs.existsSync(path.join(wfDir, 'CONCERT-WORKFLOW-OLD.md'))).toBe(false);
  });

  it('deletes stale command files', () => {
    const cmdDir = path.join(cleanupDir, '.claude', 'commands', 'concert');
    fs.mkdirSync(cmdDir, { recursive: true });
    fs.writeFileSync(
      path.join(cmdDir, 'old-cmd.md'),
      '<!-- AUTO-GENERATED BY CONCERT v0.1.0 — DO NOT EDIT. -->\n# /concert:old-cmd'
    );
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toContain(path.join('.claude', 'commands', 'concert', 'old-cmd.md'));
  });

  it('deletes stale GitHub agent stubs', () => {
    const stubDir = path.join(cleanupDir, '.github', 'agents');
    fs.mkdirSync(stubDir, { recursive: true });
    fs.writeFileSync(
      path.join(stubDir, 'concert-stale.agent.md'),
      '---\nname: concert-stale\n---\n\n<!-- AUTO-GENERATED BY CONCERT v0.2.0 — DO NOT EDIT -->\nold stub'
    );
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toContain(path.join('.github', 'agents', 'concert-stale.agent.md'));
  });

  it('deletes stale GitHub workflow files', () => {
    const wfDir = path.join(cleanupDir, '.github', 'workflows');
    fs.mkdirSync(wfDir, { recursive: true });
    fs.writeFileSync(
      path.join(wfDir, 'concert-old-action.yml'),
      '# AUTO-GENERATED BY CONCERT v0.1.0 — DO NOT EDIT.\nname: Old Action'
    );
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toContain(path.join('.github', 'workflows', 'concert-old-action.yml'));
  });

  it('deletes stale skill directories', () => {
    const skillDir = path.join(cleanupDir, '.claude', 'skills', 'old-skill');
    fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(
      path.join(skillDir, 'SKILL.md'),
      '---\n# AUTO-GENERATED BY CONCERT v0.3.0 — DO NOT EDIT.\nname: old-skill\n---\nold skill content'
    );
    fs.writeFileSync(path.join(skillDir, 'extra.md'), 'extra content');
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toContain(path.join('.claude', 'skills', 'old-skill'));
    expect(fs.existsSync(skillDir)).toBe(false);
  });

  it('leaves user-created skills untouched', () => {
    const skillDir = path.join(cleanupDir, '.claude', 'skills', 'user-skill');
    fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(path.join(skillDir, 'SKILL.md'), '# My Custom Skill\ncontent');
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toHaveLength(0);
    expect(fs.existsSync(path.join(skillDir, 'SKILL.md'))).toBe(true);
  });

  it('deletes stale rule files', () => {
    const rulesDir = path.join(cleanupDir, '.claude', 'rules');
    fs.mkdirSync(rulesDir, { recursive: true });
    fs.writeFileSync(
      path.join(rulesDir, 'old-rule.md'),
      '<!-- AUTO-GENERATED BY CONCERT v0.1.0 — DO NOT EDIT. -->\nold rule'
    );
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toContain(path.join('.claude', 'rules', 'old-rule.md'));
  });

  it('handles missing directories gracefully', () => {
    // cleanupDir is empty — no .claude, .concert, etc.
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toHaveLength(0);
  });

  it('keeps files with matching version', () => {
    const agentsDir = path.join(cleanupDir, '.claude', 'agents');
    fs.mkdirSync(agentsDir, { recursive: true });
    fs.writeFileSync(
      path.join(agentsDir, 'concert-ok.md'),
      '---\nname: concert-ok\n---\n\n<!-- AUTO-GENERATED BY CONCERT v2.0.0 — DO NOT EDIT. -->\nok content'
    );
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toHaveLength(0);
    expect(fs.existsSync(path.join(agentsDir, 'concert-ok.md'))).toBe(true);
  });

  it('keeps Concert-repo-only files with current version header', () => {
    // Files excluded from shipping (e.g. concert-ci.yml, concert-repo-managed-files.md)
    // survive cleanup because they have the current version header — no exclusion list needed.
    const wfDir = path.join(cleanupDir, '.github', 'workflows');
    const rulesDir = path.join(cleanupDir, '.claude', 'rules');
    fs.mkdirSync(wfDir, { recursive: true });
    fs.mkdirSync(rulesDir, { recursive: true });
    fs.writeFileSync(
      path.join(wfDir, 'concert-ci.yml'),
      '# AUTO-GENERATED BY CONCERT v2.0.0 — DO NOT EDIT.\nname: Concert CI'
    );
    fs.writeFileSync(
      path.join(rulesDir, 'concert-repo-managed-files.md'),
      '<!-- AUTO-GENERATED BY CONCERT v2.0.0 — DO NOT EDIT. -->\nConcert repo rule'
    );
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toHaveLength(0);
    expect(fs.existsSync(path.join(wfDir, 'concert-ci.yml'))).toBe(true);
    expect(fs.existsSync(path.join(rulesDir, 'concert-repo-managed-files.md'))).toBe(true);
  });
});
