import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import {
  copyTemplates,
  cleanupStaleFiles,
  copyLiveFiles,
  copyReadme,
  EXCLUDED_RULES,
} from '../lib/copy.js';

let tmpSrc: string;
let tmpTarget: string;

beforeEach(() => {
  tmpSrc = fs.mkdtempSync(path.join(os.tmpdir(), 'concert-copy-src-'));
  tmpTarget = fs.mkdtempSync(path.join(os.tmpdir(), 'concert-copy-target-'));
  // Create some test files in src
  fs.mkdirSync(path.join(tmpSrc, 'subdir'), { recursive: true });
  fs.writeFileSync(path.join(tmpSrc, 'file1.txt'), 'content 1');
  fs.writeFileSync(path.join(tmpSrc, 'file2.txt'), 'content 2');
  fs.writeFileSync(path.join(tmpSrc, 'subdir', 'file3.txt'), 'content 3');
});

afterEach(() => {
  fs.rmSync(tmpSrc, { recursive: true, force: true });
  fs.rmSync(tmpTarget, { recursive: true, force: true });
});

describe('copyTemplates', () => {
  it('copies all files from source to empty target', () => {
    const result = copyTemplates(tmpSrc, tmpTarget);
    expect(result.created).toHaveLength(3);
    expect(result.skipped).toHaveLength(0);
    expect(result.overwritten).toHaveLength(0);
    expect(fs.existsSync(path.join(tmpTarget, 'file1.txt'))).toBe(true);
    expect(fs.existsSync(path.join(tmpTarget, 'file2.txt'))).toBe(true);
    expect(fs.existsSync(path.join(tmpTarget, 'subdir', 'file3.txt'))).toBe(true);
  });

  it('skips existing files when overwrite is false', () => {
    // Pre-create one file
    fs.writeFileSync(path.join(tmpTarget, 'file1.txt'), 'existing content');
    const result = copyTemplates(tmpSrc, tmpTarget, false);
    expect(result.created).toHaveLength(2);
    expect(result.skipped).toHaveLength(1);
    expect(result.overwritten).toHaveLength(0);
    // Original content should remain
    expect(fs.readFileSync(path.join(tmpTarget, 'file1.txt'), 'utf-8')).toBe('existing content');
  });

  it('overwrites existing files when overwrite is true', () => {
    fs.writeFileSync(path.join(tmpTarget, 'file1.txt'), 'old content');
    const result = copyTemplates(tmpSrc, tmpTarget, true);
    expect(result.overwritten).toHaveLength(1);
    expect(fs.readFileSync(path.join(tmpTarget, 'file1.txt'), 'utf-8')).toBe('content 1');
  });

  it('creates nested directories', () => {
    const result = copyTemplates(tmpSrc, tmpTarget);
    expect(fs.existsSync(path.join(tmpTarget, 'subdir'))).toBe(true);
    expect(result.created.some((f) => f.includes('file3'))).toBe(true);
  });

  it('stamps version into managed headers when version provided', () => {
    const managedContent =
      '<!-- AUTO-GENERATED BY CONCERT v0.1.0 — DO NOT EDIT. -->\n# Template file';
    fs.writeFileSync(path.join(tmpSrc, 'managed.md'), managedContent);
    const result = copyTemplates(tmpSrc, tmpTarget, false, '2.0.0');
    expect(result.created.some((f) => f.includes('managed.md'))).toBe(true);
    const copied = fs.readFileSync(path.join(tmpTarget, 'managed.md'), 'utf-8');
    expect(copied).toContain('AUTO-GENERATED BY CONCERT v2.0.0');
    expect(copied).not.toContain('v0.1.0');
  });
});

describe('cleanupStaleFiles', () => {
  let cleanupDir: string;

  beforeEach(() => {
    cleanupDir = fs.mkdtempSync(path.join(os.tmpdir(), 'concert-cleanup-'));
  });

  afterEach(() => {
    fs.rmSync(cleanupDir, { recursive: true, force: true });
  });

  it('deletes GitHub agent files with old version', () => {
    const agentsDir = path.join(cleanupDir, '.github', 'agents');
    fs.mkdirSync(agentsDir, { recursive: true });
    fs.writeFileSync(
      path.join(agentsDir, 'concert-old.agent.md'),
      '---\nname: concert-old\n---\n\n<!-- AUTO-GENERATED BY CONCERT v0.5.0 — DO NOT EDIT. -->\nold content'
    );
    fs.writeFileSync(
      path.join(agentsDir, 'concert-current.agent.md'),
      '---\nname: concert-current\n---\n\n<!-- AUTO-GENERATED BY CONCERT v2.0.0 — DO NOT EDIT. -->\ncurrent content'
    );
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toContain(path.join('.github', 'agents', 'concert-old.agent.md'));
    expect(result.deleted).not.toContain(
      path.join('.github', 'agents', 'concert-current.agent.md')
    );
    expect(fs.existsSync(path.join(agentsDir, 'concert-old.agent.md'))).toBe(false);
    expect(fs.existsSync(path.join(agentsDir, 'concert-current.agent.md'))).toBe(true);
  });

  it('deletes stale command files', () => {
    const cmdDir = path.join(cleanupDir, '.claude', 'commands');
    fs.mkdirSync(cmdDir, { recursive: true });
    fs.writeFileSync(
      path.join(cmdDir, 'concert-old-cmd.md'),
      '<!-- AUTO-GENERATED BY CONCERT v0.1.0 — DO NOT EDIT. -->\n# /concert-old-cmd'
    );
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toContain(path.join('.claude', 'commands', 'concert-old-cmd.md'));
  });

  it('leaves non-concert files untouched', () => {
    const agentsDir = path.join(cleanupDir, '.github', 'agents');
    fs.mkdirSync(agentsDir, { recursive: true });
    fs.writeFileSync(path.join(agentsDir, 'my-custom-agent.agent.md'), '# My custom agent');
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toHaveLength(0);
    expect(fs.existsSync(path.join(agentsDir, 'my-custom-agent.agent.md'))).toBe(true);
  });

  it('leaves files without managed header untouched', () => {
    const agentsDir = path.join(cleanupDir, '.github', 'agents');
    fs.mkdirSync(agentsDir, { recursive: true });
    fs.writeFileSync(
      path.join(agentsDir, 'concert-user.agent.md'),
      '---\nname: concert-user\n---\n# User-created agent with concert- prefix'
    );
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toHaveLength(0);
    expect(fs.existsSync(path.join(agentsDir, 'concert-user.agent.md'))).toBe(true);
  });

  it('handles missing directories gracefully', () => {
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toHaveLength(0);
  });

  it('deletes files with X.Y.Z placeholder version', () => {
    const agentsDir = path.join(cleanupDir, '.github', 'agents');
    fs.mkdirSync(agentsDir, { recursive: true });
    fs.writeFileSync(
      path.join(agentsDir, 'concert-placeholder.agent.md'),
      '---\nname: concert-placeholder\n---\n\n<!-- AUTO-GENERATED BY CONCERT vX.Y.Z — DO NOT EDIT. -->\nplaceholder content'
    );
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toContain(
      path.join('.github', 'agents', 'concert-placeholder.agent.md')
    );
    expect(fs.existsSync(path.join(agentsDir, 'concert-placeholder.agent.md'))).toBe(false);
  });

  it('keeps files with matching version', () => {
    const agentsDir = path.join(cleanupDir, '.github', 'agents');
    fs.mkdirSync(agentsDir, { recursive: true });
    fs.writeFileSync(
      path.join(agentsDir, 'concert-ok.agent.md'),
      '---\nname: concert-ok\n---\n\n<!-- AUTO-GENERATED BY CONCERT v2.0.0 — DO NOT EDIT. -->\nok content'
    );
    const result = cleanupStaleFiles(cleanupDir, '2.0.0');
    expect(result.deleted).toHaveLength(0);
    expect(fs.existsSync(path.join(agentsDir, 'concert-ok.agent.md'))).toBe(true);
  });
});

describe('copyLiveFiles version stamping', () => {
  let packageRoot: string;
  let targetDir: string;

  beforeEach(() => {
    packageRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'concert-pkg-'));
    targetDir = fs.mkdtempSync(path.join(os.tmpdir(), 'concert-target-'));

    // Create minimal target structure
    fs.mkdirSync(path.join(targetDir, '.concert'), { recursive: true });

    // Create source GitHub agent files with old version headers
    const agentsDir = path.join(packageRoot, '.github', 'agents');
    fs.mkdirSync(agentsDir, { recursive: true });
    fs.writeFileSync(
      path.join(agentsDir, 'concert-test.agent.md'),
      '---\nname: concert-test\n---\n\n<!-- AUTO-GENERATED BY CONCERT v1.9.0 — DO NOT EDIT. -->\n# Test agent'
    );

    // Create source command files with old version headers
    const cmdsDir = path.join(packageRoot, '.claude', 'commands');
    fs.mkdirSync(cmdsDir, { recursive: true });
    fs.writeFileSync(
      path.join(cmdsDir, 'concert-test.md'),
      '<!-- AUTO-GENERATED BY CONCERT v1.9.0 — DO NOT EDIT. -->\n# /concert-test'
    );

    // Create source rule files
    const rulesDir = path.join(packageRoot, '.claude', 'rules');
    fs.mkdirSync(rulesDir, { recursive: true });
    fs.writeFileSync(
      path.join(rulesDir, 'concert-conventional-commits.md'),
      '<!-- AUTO-GENERATED BY CONCERT v1.9.0 — DO NOT EDIT. -->\n# Conventional Commits'
    );
    // Create excluded rule files (concert-repo-only)
    for (const excluded of EXCLUDED_RULES) {
      fs.writeFileSync(
        path.join(rulesDir, excluded),
        '<!-- AUTO-GENERATED BY CONCERT v1.9.0 — DO NOT EDIT. -->\n# Repo-only rule'
      );
    }
  });

  afterEach(() => {
    fs.rmSync(packageRoot, { recursive: true, force: true });
    fs.rmSync(targetDir, { recursive: true, force: true });
  });

  it('stamps current version into copied files when version provided', () => {
    const result = copyLiveFiles(packageRoot, targetDir, true, '2.0.0');
    expect(result.created.length).toBeGreaterThan(0);

    const copiedAgent = fs.readFileSync(
      path.join(targetDir, '.github', 'agents', 'concert-test.agent.md'),
      'utf-8'
    );
    expect(copiedAgent).toContain('AUTO-GENERATED BY CONCERT v2.0.0');
    expect(copiedAgent).not.toContain('AUTO-GENERATED BY CONCERT v1.9.0');

    const copiedCmd = fs.readFileSync(
      path.join(targetDir, '.claude', 'commands', 'concert-test.md'),
      'utf-8'
    );
    expect(copiedCmd).toContain('AUTO-GENERATED BY CONCERT v2.0.0');
  });

  it('preserves original version when no version provided', () => {
    const result = copyLiveFiles(packageRoot, targetDir, true);
    expect(result.created.length).toBeGreaterThan(0);

    const copied = fs.readFileSync(
      path.join(targetDir, '.github', 'agents', 'concert-test.agent.md'),
      'utf-8'
    );
    expect(copied).toContain('AUTO-GENERATED BY CONCERT v1.9.0');
  });

  it('stamped files survive cleanup with matching version', () => {
    copyLiveFiles(packageRoot, targetDir, true, '2.0.0');

    const result = cleanupStaleFiles(targetDir, '2.0.0');
    expect(result.deleted).toHaveLength(0);
    expect(fs.existsSync(path.join(targetDir, '.github', 'agents', 'concert-test.agent.md'))).toBe(
      true
    );
  });

  it('without stamping, cleanup deletes freshly copied files (the bug)', () => {
    copyLiveFiles(packageRoot, targetDir, true);

    const result = cleanupStaleFiles(targetDir, '2.0.0');
    expect(result.deleted.length).toBeGreaterThan(0);
    expect(fs.existsSync(path.join(targetDir, '.github', 'agents', 'concert-test.agent.md'))).toBe(
      false
    );
  });

  it('stamps current version into files with X.Y.Z placeholder', () => {
    // Overwrite source files with X.Y.Z placeholder (simulating development source files)
    fs.writeFileSync(
      path.join(packageRoot, '.github', 'agents', 'concert-test.agent.md'),
      '---\nname: concert-test\n---\n\n<!-- AUTO-GENERATED BY CONCERT vX.Y.Z — DO NOT EDIT. -->\n# Test agent'
    );
    fs.writeFileSync(
      path.join(packageRoot, '.claude', 'commands', 'concert-test.md'),
      '<!-- AUTO-GENERATED BY CONCERT vX.Y.Z — DO NOT EDIT. -->\n# /concert-test'
    );

    const result = copyLiveFiles(packageRoot, targetDir, true, '2.0.0');
    expect(result.created.length).toBeGreaterThan(0);

    const copiedAgent = fs.readFileSync(
      path.join(targetDir, '.github', 'agents', 'concert-test.agent.md'),
      'utf-8'
    );
    expect(copiedAgent).toContain('AUTO-GENERATED BY CONCERT v2.0.0');
    expect(copiedAgent).not.toContain('vX.Y.Z');

    const copiedCmd = fs.readFileSync(
      path.join(targetDir, '.claude', 'commands', 'concert-test.md'),
      'utf-8'
    );
    expect(copiedCmd).toContain('AUTO-GENERATED BY CONCERT v2.0.0');
    expect(copiedCmd).not.toContain('vX.Y.Z');
  });

  it('files stamped from X.Y.Z survive cleanup with matching version', () => {
    // Source files have X.Y.Z placeholder
    fs.writeFileSync(
      path.join(packageRoot, '.github', 'agents', 'concert-test.agent.md'),
      '---\nname: concert-test\n---\n\n<!-- AUTO-GENERATED BY CONCERT vX.Y.Z — DO NOT EDIT. -->\n# Test agent'
    );
    fs.writeFileSync(
      path.join(packageRoot, '.claude', 'commands', 'concert-test.md'),
      '<!-- AUTO-GENERATED BY CONCERT vX.Y.Z — DO NOT EDIT. -->\n# /concert-test'
    );

    copyLiveFiles(packageRoot, targetDir, true, '2.0.0');

    const result = cleanupStaleFiles(targetDir, '2.0.0');
    expect(result.deleted).toHaveLength(0);
    expect(fs.existsSync(path.join(targetDir, '.github', 'agents', 'concert-test.agent.md'))).toBe(
      true
    );
  });

  it('copies rule files and excludes concert-repo-only rules', () => {
    const result = copyLiveFiles(packageRoot, targetDir, true, '2.0.0');

    // concert-conventional-commits.md should be deployed
    expect(result.created).toContain(
      path.join('.claude', 'rules', 'concert-conventional-commits.md')
    );
    expect(
      fs.existsSync(path.join(targetDir, '.claude', 'rules', 'concert-conventional-commits.md'))
    ).toBe(true);

    // Excluded rules should NOT be deployed
    for (const excluded of EXCLUDED_RULES) {
      expect(result.created).not.toContain(path.join('.claude', 'rules', excluded));
      expect(fs.existsSync(path.join(targetDir, '.claude', 'rules', excluded))).toBe(false);
    }
  });

  it('cleanup skips excluded rule files in target repo', () => {
    const rulesDir = path.join(targetDir, '.claude', 'rules');
    fs.mkdirSync(rulesDir, { recursive: true });
    // Simulate an excluded rule file that happens to exist in the target with old version
    fs.writeFileSync(
      path.join(rulesDir, EXCLUDED_RULES[0]!),
      '<!-- AUTO-GENERATED BY CONCERT v0.5.0 — DO NOT EDIT. -->\n# Old repo rule'
    );
    const result = cleanupStaleFiles(targetDir, '2.0.0');
    // Should NOT delete excluded files
    expect(result.deleted).not.toContain(path.join('.claude', 'rules', EXCLUDED_RULES[0]!));
    expect(fs.existsSync(path.join(rulesDir, EXCLUDED_RULES[0]!))).toBe(true);
  });

  it('cleanup deletes stale rule files that are not excluded', () => {
    const rulesDir = path.join(targetDir, '.claude', 'rules');
    fs.mkdirSync(rulesDir, { recursive: true });
    fs.writeFileSync(
      path.join(rulesDir, 'concert-old-rule.md'),
      '<!-- AUTO-GENERATED BY CONCERT v0.5.0 — DO NOT EDIT. -->\n# Old rule'
    );
    const result = cleanupStaleFiles(targetDir, '2.0.0');
    expect(result.deleted).toContain(path.join('.claude', 'rules', 'concert-old-rule.md'));
    expect(fs.existsSync(path.join(rulesDir, 'concert-old-rule.md'))).toBe(false);
  });

  it('only copies files matching the pattern', () => {
    // Add a non-matching file to the agents dir
    fs.writeFileSync(
      path.join(packageRoot, '.github', 'agents', 'not-concert.md'),
      '# Not a concert agent'
    );
    const result = copyLiveFiles(packageRoot, targetDir, true, '2.0.0');
    // Non-matching file should NOT be copied
    expect(fs.existsSync(path.join(targetDir, '.github', 'agents', 'not-concert.md'))).toBe(false);
    // Excluded rule files should NOT be copied
    for (const excluded of EXCLUDED_RULES) {
      expect(result.created).not.toContain(path.join('.claude', 'rules', excluded));
    }
  });
});

describe('copyReadme', () => {
  let pkgRoot: string;
  let targetDir: string;

  beforeEach(() => {
    pkgRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'concert-readme-src-'));
    targetDir = fs.mkdtempSync(path.join(os.tmpdir(), 'concert-readme-target-'));
  });

  afterEach(() => {
    fs.rmSync(pkgRoot, { recursive: true, force: true });
    fs.rmSync(targetDir, { recursive: true, force: true });
  });

  it('copies README.md to .concert/ when it does not exist', () => {
    fs.writeFileSync(path.join(pkgRoot, 'README.md'), '# Concert\n\nReadme content.');
    fs.mkdirSync(path.join(targetDir, '.concert'), { recursive: true });

    const result = copyReadme(pkgRoot, targetDir, false);

    expect(result.created).toContain(path.join('.concert', 'README.md'));
    expect(result.skipped).toHaveLength(0);
    expect(result.overwritten).toHaveLength(0);
    expect(fs.readFileSync(path.join(targetDir, '.concert', 'README.md'), 'utf-8')).toBe(
      '# Concert\n\nReadme content.'
    );
  });

  it('skips existing README.md when overwrite is false', () => {
    fs.writeFileSync(path.join(pkgRoot, 'README.md'), '# Concert\n\nNew content.');
    fs.mkdirSync(path.join(targetDir, '.concert'), { recursive: true });
    fs.writeFileSync(path.join(targetDir, '.concert', 'README.md'), '# Old content');

    const result = copyReadme(pkgRoot, targetDir, false);

    expect(result.skipped).toContain(path.join('.concert', 'README.md'));
    expect(result.created).toHaveLength(0);
    expect(result.overwritten).toHaveLength(0);
    expect(fs.readFileSync(path.join(targetDir, '.concert', 'README.md'), 'utf-8')).toBe(
      '# Old content'
    );
  });

  it('overwrites existing README.md when overwrite is true', () => {
    fs.writeFileSync(path.join(pkgRoot, 'README.md'), '# Concert\n\nUpdated content.');
    fs.mkdirSync(path.join(targetDir, '.concert'), { recursive: true });
    fs.writeFileSync(path.join(targetDir, '.concert', 'README.md'), '# Old content');

    const result = copyReadme(pkgRoot, targetDir, true);

    expect(result.overwritten).toContain(path.join('.concert', 'README.md'));
    expect(result.created).toHaveLength(0);
    expect(result.skipped).toHaveLength(0);
    expect(fs.readFileSync(path.join(targetDir, '.concert', 'README.md'), 'utf-8')).toBe(
      '# Concert\n\nUpdated content.'
    );
  });

  it('creates .concert/ directory if it does not exist', () => {
    fs.writeFileSync(path.join(pkgRoot, 'README.md'), '# Concert\n\nReadme content.');

    const result = copyReadme(pkgRoot, targetDir, false);

    expect(fs.existsSync(path.join(targetDir, '.concert'))).toBe(true);
    expect(result.created).toContain(path.join('.concert', 'README.md'));
  });

  it('returns empty result when source README.md does not exist', () => {
    const result = copyReadme(pkgRoot, targetDir, false);

    expect(result.created).toHaveLength(0);
    expect(result.skipped).toHaveLength(0);
    expect(result.overwritten).toHaveLength(0);
  });
});
