import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as jsonc from 'jsonc-parser';

const ROOT = path.resolve(__dirname, '../..');
const TEMPLATES_DIR = path.join(ROOT, 'templates');

// ======================================================================
// 1. Template files (defaults for init)
// ======================================================================

describe('template files', () => {
  it('concert.jsonc is parseable', () => {
    const configPath = path.join(TEMPLATES_DIR, 'concert.jsonc');
    expect(fs.existsSync(configPath)).toBe(true);
    const content = fs.readFileSync(configPath, 'utf-8');
    const errors: jsonc.ParseError[] = [];
    jsonc.parse(content, errors, { allowTrailingComma: true });
    expect(errors).toHaveLength(0);
  });

  it('state.json is valid JSON with required fields', () => {
    const statePath = path.join(TEMPLATES_DIR, '.concert', 'state.json');
    expect(fs.existsSync(statePath)).toBe(true);
    const state = JSON.parse(fs.readFileSync(statePath, 'utf-8'));
    for (const field of [
      'mission',
      'branch',
      'pr_number',
      'stage',
      'pipeline',
      'phases_completed',
      'tasks_completed',
      'commits',
      'cost',
      'next_action',
      'blockers',
      'telemetry',
      'failure_log',
      'history',
      'next_steps',
    ]) {
      expect(state, `Missing: ${field}`).toHaveProperty(field);
    }
  });

  it('CLAUDE.md has CONCERT:START and CONCERT:END markers', () => {
    const claudePath = path.join(TEMPLATES_DIR, 'CLAUDE.md');
    expect(fs.existsSync(claudePath)).toBe(true);
    const content = fs.readFileSync(claudePath, 'utf-8');
    expect(content).toContain('CONCERT:START');
    expect(content).toContain('CONCERT:END');
  });

  it('.concert/missions/.gitkeep exists', () => {
    expect(fs.existsSync(path.join(TEMPLATES_DIR, '.concert', 'missions', '.gitkeep'))).toBe(true);
  });

  it('.concert/TODO.md exists with ad hoc description', () => {
    const todoPath = path.join(TEMPLATES_DIR, '.concert', 'TODO.md');
    expect(fs.existsSync(todoPath)).toBe(true);
    const content = fs.readFileSync(todoPath, 'utf-8');
    expect(content).toContain('TODO');
    expect(content).toContain('should NOT');
  });

  it('.concert/IDEAS.md exists with ad hoc description', () => {
    const ideasPath = path.join(TEMPLATES_DIR, '.concert', 'IDEAS.md');
    expect(fs.existsSync(ideasPath)).toBe(true);
    const content = fs.readFileSync(ideasPath, 'utf-8');
    expect(content).toContain('Ideas');
    expect(content).toContain('should NOT');
  });

  it('no file in templates exceeds 50KB', () => {
    function checkSize(dir: string): void {
      if (!fs.existsSync(dir)) return;
      const entries = fs.readdirSync(dir, { withFileTypes: true });
      for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory()) {
          checkSize(fullPath);
        } else {
          const stats = fs.statSync(fullPath);
          expect(stats.size, `${fullPath} exceeds 50KB`).toBeLessThan(50 * 1024);
        }
      }
    }
    checkSize(TEMPLATES_DIR);
  });
});

// ======================================================================
// 2. GitHub agent files (live)
// ======================================================================

describe('GitHub agent files (live)', () => {
  const agentsDir = path.join(ROOT, '.github', 'agents');

  it('.github/agents directory exists', () => {
    expect(fs.existsSync(agentsDir)).toBe(true);
  });

  const agentFiles = fs.existsSync(agentsDir)
    ? fs.readdirSync(agentsDir).filter((f) => f.startsWith('concert-') && f.endsWith('.agent.md'))
    : [];

  it('has at least 1 concert agent', () => {
    expect(agentFiles.length).toBeGreaterThanOrEqual(1);
  });

  for (const file of agentFiles) {
    it(`${file} has managed header and frontmatter`, () => {
      const filePath = path.join(agentsDir, file);
      const content = fs.readFileSync(filePath, 'utf-8');
      expect(content).toMatch(/AUTO-GENERATED BY CONCERT/);
      expect(content).toContain('name:');
      expect(content).toContain('description:');
    });

    it(`${file} has YAML frontmatter on line 1`, () => {
      const filePath = path.join(agentsDir, file);
      const content = fs.readFileSync(filePath, 'utf-8');
      expect(content.startsWith('---\n'), `${file} must start with --- (YAML frontmatter)`).toBe(
        true
      );
    });
  }
});

// ======================================================================
// 3. Claude command files (live)
// ======================================================================

describe('Claude command files (live)', () => {
  const commandsDir = path.join(ROOT, '.claude', 'commands');

  it('.claude/commands directory exists', () => {
    expect(fs.existsSync(commandsDir)).toBe(true);
  });

  const commandFiles = fs.existsSync(commandsDir)
    ? fs.readdirSync(commandsDir).filter((f) => f.startsWith('concert-') && f.endsWith('.md'))
    : [];

  it('has at least 1 concert command', () => {
    expect(commandFiles.length).toBeGreaterThanOrEqual(1);
  });

  for (const file of commandFiles) {
    it(`${file} has managed header`, () => {
      const filePath = path.join(commandsDir, file);
      const content = fs.readFileSync(filePath, 'utf-8');
      expect(content).toMatch(/AUTO-GENERATED BY CONCERT/);
    });
  }
});

// ======================================================================
// 4. Claude rule files (live)
// ======================================================================

describe('Claude rule files (live)', () => {
  const rulesDir = path.join(ROOT, '.claude', 'rules');

  it('.claude/rules directory exists', () => {
    expect(fs.existsSync(rulesDir)).toBe(true);
  });

  const ruleFiles = fs.existsSync(rulesDir)
    ? fs.readdirSync(rulesDir).filter((f) => f.startsWith('concert-') && f.endsWith('.md'))
    : [];

  it('has at least 1 concert rule', () => {
    expect(ruleFiles.length).toBeGreaterThanOrEqual(1);
  });

  it('includes concert-conventional-commits.md', () => {
    expect(ruleFiles).toContain('concert-conventional-commits.md');
  });

  for (const file of ruleFiles) {
    it(`${file} has managed header`, () => {
      const filePath = path.join(rulesDir, file);
      const content = fs.readFileSync(filePath, 'utf-8');
      expect(content).toMatch(/AUTO-GENERATED BY CONCERT/);
    });
  }
});
