import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as jsonc from 'jsonc-parser';

const ROOT = path.resolve(__dirname, '../..');
const TEMPLATES_DIR = path.join(ROOT, 'templates');

// ======================================================================
// 1. Template files (defaults for init)
// ======================================================================

describe('template files', () => {
  it('concert.jsonc is parseable', () => {
    const configPath = path.join(TEMPLATES_DIR, 'concert.jsonc');
    expect(fs.existsSync(configPath)).toBe(true);
    const content = fs.readFileSync(configPath, 'utf-8');
    const errors: jsonc.ParseError[] = [];
    jsonc.parse(content, errors, { allowTrailingComma: true });
    expect(errors).toHaveLength(0);
  });

  it('state.json is valid JSON with required fields', () => {
    const statePath = path.join(TEMPLATES_DIR, '.concert', 'state.json');
    expect(fs.existsSync(statePath)).toBe(true);
    const state = JSON.parse(fs.readFileSync(statePath, 'utf-8'));
    for (const field of [
      'mission',
      'branch',
      'pr_number',
      'stage',
      'pipeline',
      'phases_completed',
      'tasks_completed',
      'commits',
      'cost',
      'next_action',
      'blockers',
      'telemetry',
      'failure_log',
      'history',
      'next_steps',
    ]) {
      expect(state, `Missing: ${field}`).toHaveProperty(field);
    }
  });

  it('CLAUDE.md has CONCERT:START and CONCERT:END markers', () => {
    const claudePath = path.join(TEMPLATES_DIR, 'CLAUDE.md');
    expect(fs.existsSync(claudePath)).toBe(true);
    const content = fs.readFileSync(claudePath, 'utf-8');
    expect(content).toContain('CONCERT:START');
    expect(content).toContain('CONCERT:END');
  });

  it('.concert/README.md exists', () => {
    expect(fs.existsSync(path.join(TEMPLATES_DIR, '.concert', 'README.md'))).toBe(true);
  });

  it('.concert/missions/.gitkeep exists', () => {
    expect(fs.existsSync(path.join(TEMPLATES_DIR, '.concert', 'missions', '.gitkeep'))).toBe(true);
  });

  it('.concert/TODO.md exists with ad hoc description', () => {
    const todoPath = path.join(TEMPLATES_DIR, '.concert', 'TODO.md');
    expect(fs.existsSync(todoPath)).toBe(true);
    const content = fs.readFileSync(todoPath, 'utf-8');
    expect(content).toContain('TODO');
    expect(content).toContain('should NOT');
  });

  it('.concert/IDEAS.md exists with ad hoc description', () => {
    const ideasPath = path.join(TEMPLATES_DIR, '.concert', 'IDEAS.md');
    expect(fs.existsSync(ideasPath)).toBe(true);
    const content = fs.readFileSync(ideasPath, 'utf-8');
    expect(content).toContain('Ideas');
    expect(content).toContain('should NOT');
  });

  it('no file in templates exceeds 50KB', () => {
    function checkSize(dir: string): void {
      if (!fs.existsSync(dir)) return;
      const entries = fs.readdirSync(dir, { withFileTypes: true });
      for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory()) {
          checkSize(fullPath);
        } else {
          const stats = fs.statSync(fullPath);
          expect(stats.size, `${fullPath} exceeds 50KB`).toBeLessThan(50 * 1024);
        }
      }
    }
    checkSize(TEMPLATES_DIR);
  });
});

// ======================================================================
// 2. GitHub Actions workflow files (live)
// ======================================================================

describe('GitHub Actions workflow files (live)', () => {
  it('concert-ci.yml exists with managed header', () => {
    const ciPath = path.join(ROOT, '.github', 'workflows', 'concert-ci.yml');
    expect(fs.existsSync(ciPath)).toBe(true);
    const content = fs.readFileSync(ciPath, 'utf-8');
    expect(content).toMatch(/# AUTO-GENERATED BY CONCERT/);
    expect(content).toContain('concert/**');
  });

  it('concert-version-check.yml exists with managed header', () => {
    const vcPath = path.join(ROOT, '.github', 'workflows', 'concert-version-check.yml');
    expect(fs.existsSync(vcPath)).toBe(true);
    const content = fs.readFileSync(vcPath, 'utf-8');
    expect(content).toMatch(/# AUTO-GENERATED BY CONCERT/);
  });
});

// ======================================================================
// 3. Live agent definition files
// ======================================================================

// Dynamically discover all agent files with the managed header
// instead of maintaining a hardcoded list.
const agentFiles = fs
  .readdirSync(path.join(ROOT, '.claude', 'agents'))
  .filter((f) => f.startsWith('concert-') && f.endsWith('.md'));
const DISCOVERED_AGENTS = agentFiles.map((f) => f.replace('.md', ''));

describe('agent definition files (live)', () => {
  it('has at least 20 agents', () => {
    expect(DISCOVERED_AGENTS.length).toBeGreaterThanOrEqual(20);
  });

  for (const agent of DISCOVERED_AGENTS) {
    it(`${agent}.md exists with managed header and frontmatter`, () => {
      const filePath = path.join(ROOT, '.claude', 'agents', `${agent}.md`);
      expect(fs.existsSync(filePath)).toBe(true);
      const content = fs.readFileSync(filePath, 'utf-8');
      expect(content).toMatch(/AUTO-GENERATED BY CONCERT/);
      expect(content).toContain('name:');
      expect(content).toContain('description:');
      expect(content).not.toContain('tools:');
      expect(content).not.toContain('\nmodel:');
      expect(content).not.toContain('interactive_only:');
    });

    it(`${agent}.md has YAML frontmatter on line 1`, () => {
      const filePath = path.join(ROOT, '.claude', 'agents', `${agent}.md`);
      const content = fs.readFileSync(filePath, 'utf-8');
      expect(
        content.startsWith('---\n'),
        `${agent}.md must start with --- (YAML frontmatter)`
      ).toBe(true);
    });

    it(`${agent}.md has version in managed header`, () => {
      const filePath = path.join(ROOT, '.claude', 'agents', `${agent}.md`);
      const content = fs.readFileSync(filePath, 'utf-8');
      expect(content).toMatch(/AUTO-GENERATED BY CONCERT v\d+\.\d+\.\d+/);
    });
  }
});

// ======================================================================
// 4. GitHub agent stubs (live)
// ======================================================================

describe('GitHub agent stubs (live)', () => {
  for (const agent of DISCOVERED_AGENTS) {
    it(`${agent}.agent.md exists with correct format`, () => {
      const stubPath = path.join(ROOT, '.github', 'agents', `${agent}.agent.md`);
      expect(fs.existsSync(stubPath)).toBe(true);
      const content = fs.readFileSync(stubPath, 'utf-8');
      expect(content).toMatch(/AUTO-GENERATED BY CONCERT/);
      expect(content).toContain('name:');
      expect(content).toContain('description:');
      expect(content).not.toContain('tools:');
      expect(content).not.toContain('\nmodel:');
    });

    it(`${agent}.agent.md has YAML frontmatter on line 1`, () => {
      const stubPath = path.join(ROOT, '.github', 'agents', `${agent}.agent.md`);
      const content = fs.readFileSync(stubPath, 'utf-8');
      expect(
        content.startsWith('---\n'),
        `${agent}.agent.md must start with --- (YAML frontmatter)`
      ).toBe(true);
    });

    it(`${agent}.agent.md has version in managed header`, () => {
      const stubPath = path.join(ROOT, '.github', 'agents', `${agent}.agent.md`);
      const content = fs.readFileSync(stubPath, 'utf-8');
      expect(content).toMatch(/AUTO-GENERATED BY CONCERT v\d+\.\d+\.\d+/);
    });
  }
});

// ======================================================================
// 5. Claude Code command files (live)
// ======================================================================

// Dynamically discover all command files with managed header
const commandFiles = fs
  .readdirSync(path.join(ROOT, '.claude', 'commands', 'concert'))
  .filter((f) => f.endsWith('.md'));
const DISCOVERED_COMMANDS = commandFiles.map((f) => f.replace('.md', ''));

describe('Claude Code command files (live)', () => {
  it('has at least 10 commands', () => {
    expect(DISCOVERED_COMMANDS.length).toBeGreaterThanOrEqual(10);
  });

  for (const cmd of DISCOVERED_COMMANDS) {
    it(`${cmd}.md exists with managed header`, () => {
      const cmdPath = path.join(ROOT, '.claude', 'commands', 'concert', `${cmd}.md`);
      expect(fs.existsSync(cmdPath)).toBe(true);
      const content = fs.readFileSync(cmdPath, 'utf-8');
      expect(content).toMatch(/AUTO-GENERATED BY CONCERT v\d+\.\d+\.\d+/);
    });
  }
});

// ======================================================================
// 6. Workflow files (live)
// ======================================================================

// Dynamically discover all workflow files with managed header
const workflowFiles = fs
  .readdirSync(path.join(ROOT, '.concert', 'workflows'))
  .filter((f) => f.startsWith('CONCERT-WORKFLOW-') && f.endsWith('.md'));
const DISCOVERED_WORKFLOWS = workflowFiles.map((f) => f.replace('.md', ''));

describe('workflow files (live)', () => {
  it('has at least 5 workflows', () => {
    expect(DISCOVERED_WORKFLOWS.length).toBeGreaterThanOrEqual(5);
  });

  for (const wf of DISCOVERED_WORKFLOWS) {
    it(`${wf}.md exists with managed header and version`, () => {
      const wfPath = path.join(ROOT, '.concert', 'workflows', `${wf}.md`);
      expect(fs.existsSync(wfPath)).toBe(true);
      const content = fs.readFileSync(wfPath, 'utf-8');
      expect(content).toMatch(/AUTO-GENERATED BY CONCERT v\d+\.\d+\.\d+/);
    });
  }
});

// ======================================================================
// 7. Skill files (live)
// ======================================================================

describe('skill files (live)', () => {
  const skillsDir = path.join(ROOT, '.claude', 'skills');
  const skills = fs
    .readdirSync(skillsDir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name);

  it('has at least 3 skills', () => {
    expect(skills.length).toBeGreaterThanOrEqual(3);
  });

  for (const skill of skills) {
    it(`${skill}/SKILL.md exists with managed header and version`, () => {
      const skillPath = path.join(skillsDir, skill, 'SKILL.md');
      expect(fs.existsSync(skillPath)).toBe(true);
      const content = fs.readFileSync(skillPath, 'utf-8');
      expect(content).toMatch(/AUTO-GENERATED BY CONCERT v\d+\.\d+\.\d+/);
    });
  }
});

// ======================================================================
// 8. Rule files (live)
// ======================================================================

describe('rule files (live)', () => {
  const rulesDir = path.join(ROOT, '.claude', 'rules');

  it('has at least 1 rule', () => {
    const rules = fs.readdirSync(rulesDir).filter((f) => f.endsWith('.md'));
    expect(rules.length).toBeGreaterThanOrEqual(1);
  });

  it('conventional-commits.md exists', () => {
    const rulePath = path.join(rulesDir, 'conventional-commits.md');
    expect(fs.existsSync(rulePath)).toBe(true);
  });
});

// ======================================================================
// 9. Stage registry
// ======================================================================

describe('stage registry', () => {
  const registryPath = path.join(ROOT, '.concert', 'stage-registry.jsonc');

  it('stage-registry.jsonc exists and is valid JSONC', () => {
    expect(fs.existsSync(registryPath)).toBe(true);
    const content = fs.readFileSync(registryPath, 'utf-8');
    const errors: jsonc.ParseError[] = [];
    const registry = jsonc.parse(content, errors, { allowTrailingComma: true });
    expect(errors).toHaveLength(0);
    expect(registry).toHaveProperty('stages');
    expect(registry).toHaveProperty('workflows');
  });

  it('all stages have required fields', () => {
    const content = fs.readFileSync(registryPath, 'utf-8');
    const registry = jsonc.parse(content, undefined, { allowTrailingComma: true });
    const requiredFields = [
      'name',
      'order',
      'agent',
      'inputs',
      'outputs',
      'output_template',
      'triggers_review',
      'produces_spec',
      'interactive',
      'display_name',
    ];
    for (const stage of registry.stages) {
      for (const field of requiredFields) {
        expect(stage, `Stage "${stage.name}" missing field "${field}"`).toHaveProperty(field);
      }
    }
  });

  it('all referenced agent files exist', () => {
    const content = fs.readFileSync(registryPath, 'utf-8');
    const registry = jsonc.parse(content, undefined, { allowTrailingComma: true });
    const agentsDir = path.join(ROOT, '.claude', 'agents');
    for (const stage of registry.stages) {
      if (stage.agent === null) continue; // stage not yet implemented
      const agentPath = path.join(agentsDir, stage.agent);
      expect(
        fs.existsSync(agentPath),
        `Missing agent for stage "${stage.name}": ${stage.agent}`
      ).toBe(true);
    }
  });

  it('stage names are unique', () => {
    const content = fs.readFileSync(registryPath, 'utf-8');
    const registry = jsonc.parse(content, undefined, { allowTrailingComma: true });
    const names = registry.stages.map((s: { name: string }) => s.name);
    expect(new Set(names).size).toBe(names.length);
  });

  it('stage orders are sequential starting from 1', () => {
    const content = fs.readFileSync(registryPath, 'utf-8');
    const registry = jsonc.parse(content, undefined, { allowTrailingComma: true });
    const orders = registry.stages
      .map((s: { order: number }) => s.order)
      .sort((a: number, b: number) => a - b);
    for (let i = 0; i < orders.length; i++) {
      expect(orders[i]).toBe(i + 1);
    }
  });
});

// ======================================================================
// 10. Workflow-registry consistency
// ======================================================================

describe('workflow-registry consistency', () => {
  const registryPath = path.join(ROOT, '.concert', 'stage-registry.jsonc');
  const content = fs.readFileSync(registryPath, 'utf-8');
  const registry = jsonc.parse(content, undefined, { allowTrailingComma: true });
  const stageNames = new Set(registry.stages.map((s: { name: string }) => s.name));

  it('all workflow variants reference valid stage names', () => {
    for (const [variant, stages] of Object.entries(registry.workflows)) {
      for (const stage of stages as string[]) {
        expect(
          stageNames.has(stage),
          `Workflow "${variant}" references unknown stage "${stage}"`
        ).toBe(true);
      }
    }
  });

  const workflowFiles = [
    { name: 'mission-full', file: 'CONCERT-WORKFLOW-MISSION-FULL.md' },
    { name: 'mission-medium', file: 'CONCERT-WORKFLOW-MISSION-MEDIUM.md' },
    { name: 'mission-small', file: 'CONCERT-WORKFLOW-MISSION-SMALL.md' },
  ];

  for (const { name, file } of workflowFiles) {
    it(`${file} Stages line matches registry workflows.${name}`, () => {
      const workflowPath = path.join(ROOT, '.concert', 'workflows', file);
      expect(fs.existsSync(workflowPath)).toBe(true);
      const workflowContent = fs.readFileSync(workflowPath, 'utf-8');
      const match = workflowContent.match(/^Stages:\s*(.+)$/m);
      expect(match, `No "Stages:" line found in ${file}`).not.toBeNull();
      const fileStages = match![1].split(',').map((s: string) => s.trim());
      const registryStages = registry.workflows[name];
      expect(fileStages, `${file} stages don't match registry`).toEqual(registryStages);
    });
  }
});

// ======================================================================
// 11. User guidance templates
// ======================================================================

describe('user guidance templates', () => {
  const templatesDir = path.join(ROOT, '.concert', 'templates');

  it('user-guidance.md exists with managed header', () => {
    const templatePath = path.join(templatesDir, 'user-guidance.md');
    expect(fs.existsSync(templatePath)).toBe(true);
    const content = fs.readFileSync(templatePath, 'utf-8');
    expect(content).toMatch(/AUTO-GENERATED BY CONCERT/);
  });

  it('user-guidance.md contains expected template sections', () => {
    const templatePath = path.join(templatesDir, 'user-guidance.md');
    const content = fs.readFileSync(templatePath, 'utf-8');
    const expectedSections = [
      'Stage Draft Complete',
      'Stage Accepted',
      'Review Prompt',
      'Mission Initialized',
      'Mission Deleted',
      'Replan Complete',
      'Restart Complete',
      'Fix Complete',
      'Fix Escalated',
      'Debug Complete',
      'Debug Escalated',
      'Quick Complete',
      'Code Review Pass',
      'Code Review Fail',
      'Coder Task Complete',
      'Coder Task Failed',
      'Documentation Updated',
      'Verification Complete',
      'Failure Recovery',
      'Mission Status',
    ];
    for (const section of expectedSections) {
      expect(content, `Missing template section: "${section}"`).toContain(section);
    }
  });
});

// ======================================================================
// 12. Cross-reference consistency
// ======================================================================

describe('cross-reference consistency', () => {
  it('every GitHub stub references an existing agent definition', () => {
    const stubsDir = path.join(ROOT, '.github', 'agents');
    const agentsDir = path.join(ROOT, '.claude', 'agents');
    const stubs = fs.readdirSync(stubsDir).filter((f) => f.endsWith('.agent.md'));
    for (const stub of stubs) {
      const agentName = stub.replace('.agent.md', '');
      const agentPath = path.join(agentsDir, `${agentName}.md`);
      expect(fs.existsSync(agentPath), `Missing agent for stub: ${stub}`).toBe(true);
    }
  });
});
