import { describe, it, expect } from 'vitest';
import type {
  ConcertState,
  ConcertConfig,
  TaskFrontmatter,
  TelemetryRecord,
  FailureBlock,
  HistoryEntry,
  ReviewFinding,
  QualityLoopState,
  DebugState,
  DebugHypothesis,
} from '../types.js';
import {
  MANAGED_HEADER_PREFIX,
  MANAGED_HEADER_MD,
  MANAGED_HEADER_YAML,
  CLAUDE_SECTION_START,
  CLAUDE_SECTION_END,
} from '../types.js';

describe('types', () => {
  it('ConcertState interface can be instantiated', () => {
    const state: ConcertState = {
      mission: 'test-mission',
      mission_path: '.concert/missions/test',
      workflow: 'mission-full',
      workflow_path: '.concert/workflows/CONCERT-WORKFLOW-MISSION-FULL.md',
      branch: 'concert/test',
      pr_number: 42,
      status_display: 'wip_pr',
      feature_size: 'large',
      stage: 'execution',
      pipeline: { vision: 'accepted', requirements: 'accepted' },
      phases_completed: 1,
      phases_total: 5,
      tasks_completed: 3,
      tasks_total: 31,
      commits: 5,
      cost: {
        estimated_remaining: '$10',
        spent_this_mission: '$5',
        by_stage: { vision: '$1' },
      },
      blockers: [],
      telemetry: [],
      failure_log: [],
      history: [],
      next_steps: ['run something'],
    };
    expect(state.mission).toBe('test-mission');
    expect(state.pr_number).toBe(42);
    expect(state.feature_size).toBe('large');
  });

  it('ConcertConfig interface can be instantiated', () => {
    const config: ConcertConfig = {
      project_name: 'my-project',
      concert_version: '0.1.0',
    };
    expect(config.project_name).toBe('my-project');
    expect(config.concert_version).toBe('0.1.0');
  });

  it('TaskFrontmatter interface can be instantiated', () => {
    const fm: TaskFrontmatter = {
      task: 'my-task',
      title: 'My Task Title',
      depends_on: ['prior-task'],
      wave: 2,
      model: 'simple',
    };
    expect(fm.task).toBe('my-task');
    expect(fm.model).toBe('simple');
  });

  it('TelemetryRecord interface can be instantiated', () => {
    const record: TelemetryRecord = {
      task_file: 'TASK-foo.md',
      task_index: 1,
      phase: 1,
      model_assigned: 'average',
      confidence: 'high',
      review_result: 'PASS',
      revision_count: 1,
      skills_loaded: ['typescript-standards'],
      files_changed: 3,
      completed_at: '2026-03-27T10:00:00Z',
    };
    expect(record.review_result).toBe('PASS');
  });

  it('FailureBlock interface can be instantiated', () => {
    const block: FailureBlock = {
      phase: 1,
      phase_name: 'Foundation',
      task_file: 'TASK-foo.md',
      task_index: 1,
      task_title: 'Build foo',
      failed_at: '2026-03-27T10:00:00Z',
      error_type: 'test_failure',
      error_summary: 'Tests failed',
      files_touched: ['src/foo.ts'],
      last_successful_commit: 'abc1234',
    };
    expect(block.error_type).toBe('test_failure');
  });

  it('ReviewFinding interface can be instantiated', () => {
    const finding: ReviewFinding = {
      severity: 'MAJ',
      file: 'src/foo.ts',
      line: 42,
      issue: 'Missing null check',
      resolved: false,
    };
    expect(finding.severity).toBe('MAJ');
  });

  it('QualityLoopState interface can be instantiated', () => {
    const qls: QualityLoopState = {
      task_file: 'TASK-foo.md',
      task_index: 1,
      iteration: 2,
      phase: 'reviewer',
      prior_findings: [],
      coder_commits: ['abc1234'],
    };
    expect(qls.phase).toBe('reviewer');
  });

  it('DebugState and DebugHypothesis interfaces can be instantiated', () => {
    const hyp: DebugHypothesis = {
      id: 1,
      description: 'The bug is in foo',
      status: 'pending',
    };
    const debug: DebugState = {
      failure_ref: 'failure-1',
      hypotheses: [hyp],
      current_hypothesis: 1,
      experiments_run: 0,
    };
    expect(debug.failure_ref).toBe('failure-1');
  });

  it('HistoryEntry interface can be instantiated', () => {
    const entry: HistoryEntry = {
      action: 'mission_created',
      timestamp: '2026-03-27',
      details: 'Created mission',
    };
    expect(entry.action).toBe('mission_created');
  });

  it('MANAGED_HEADER_PREFIX is correct', () => {
    expect(MANAGED_HEADER_PREFIX).toBe('AUTO-GENERATED BY CONCERT');
  });

  it('MANAGED_HEADER_MD generates correct string', () => {
    const header = MANAGED_HEADER_MD('0.1.0');
    expect(header).toContain('AUTO-GENERATED BY CONCERT v0.1.0');
    expect(header).toContain('concert update');
    expect(header.startsWith('<!--')).toBe(true);
  });

  it('MANAGED_HEADER_YAML generates correct string', () => {
    const header = MANAGED_HEADER_YAML('0.1.0');
    expect(header).toContain('AUTO-GENERATED BY CONCERT v0.1.0');
    expect(header.startsWith('#')).toBe(true);
  });

  it('CLAUDE_SECTION_START contains CONCERT:START', () => {
    expect(CLAUDE_SECTION_START).toContain('CONCERT:START');
  });

  it('CLAUDE_SECTION_END contains CONCERT:END', () => {
    expect(CLAUDE_SECTION_END).toContain('CONCERT:END');
  });
});
