// === State Schema (DR-001) ===

export interface ReviewFinding {
  severity: 'CRIT' | 'MAJ' | 'MIN' | 'NTH';
  file: string;
  line: number;
  issue: string;
  resolved: boolean;
}

export interface QualityLoopState {
  task_file: string;
  task_index: number;
  iteration: number;
  phase: 'coder' | 'reviewer';
  prior_findings: ReviewFinding[];
  coder_commits: string[];
}

export interface FailureBlock {
  phase: number;
  phase_name: string;
  task_file: string;
  task_index: number;
  task_title: string;
  failed_at: string; // ISO 8601
  error_type: ErrorType;
  error_summary: string;
  files_touched: string[];
  last_successful_commit: string;
}

export type ErrorType =
  | 'test_failure'
  | 'build_error'
  | 'context_exhaustion'
  | 'dependency_missing'
  | 'model_capability_exceeded'
  | 'timeout'
  | 'unknown';

export interface DebugHypothesis {
  id: number;
  description: string;
  status: 'pending' | 'testing' | 'confirmed' | 'rejected';
  result?: string;
}

export interface DebugState {
  failure_ref: string;
  hypotheses: DebugHypothesis[];
  current_hypothesis: number;
  experiments_run: number;
}

export interface TelemetryRecord {
  task_file: string;
  task_index: number;
  phase: number;
  model_assigned: ModelTier;
  confidence: 'high' | 'medium' | 'low';
  review_result: 'PASS' | 'NTH' | 'MIN' | 'MAJ' | 'CRIT' | 'none';
  revision_count: number;
  skills_loaded: string[];
  files_changed: number;
  completed_at: string; // ISO 8601
}

export interface FailureSummary {
  phase: number;
  task_file: string;
  task_index: number;
  error_type: ErrorType;
  error_summary: string;
  occurred_at: string; // ISO 8601
  resolved: boolean;
}

export interface HistoryEntry {
  action: string;
  timestamp: string;
  details: string;
}

export type PipelineStatus = 'pending' | 'draft' | 'accepted';

export interface CostTracking {
  estimated_remaining: string;
  spent_this_mission: string;
  by_stage: Record<string, string>;
}

export type NextActionType = 'run_agent' | 'run_workflow' | 'await_user';

export interface NextAction {
  type: NextActionType;
  target: string;
  context?: Record<string, string>;
  message: string;
}

export interface ConcertState {
  // Identity
  mission: string;
  mission_path: string;
  workflow: string;
  workflow_path: string;
  branch: string;
  pr_number: number;
  status_display: string;
  feature_size: 'small' | 'medium' | 'large' | '';

  // Pipeline
  stage: string;
  pipeline: Record<string, PipelineStatus>;

  // Execution progress
  phases_completed: number;
  phases_total: number;
  tasks_completed: number;
  tasks_total: number;
  commits: number;
  current_phase?: number;
  current_task_file?: string;
  current_task_index?: number;

  // Cost tracking
  cost: CostTracking;

  // Session continuation
  next_action?: NextAction | null;

  // Active states (nullable)
  failure?: FailureBlock | null;
  debug_state?: DebugState | null;
  quality_loop_state?: QualityLoopState | null;

  // Logs
  blockers: string[];
  telemetry: TelemetryRecord[];
  failure_log: FailureSummary[];
  history: HistoryEntry[];
  next_steps: string[];
}

// === Config Schema ===
//
// `concert.jsonc` is intentionally tiny — only fields that are read by
// Concert itself live here. The historical schema (execution, gates,
// model_profiles, etc.) was never read by any code path and has been
// removed. Add a field here only when a CLI command or agent actually
// reads it.

export type ModelTier = 'haiku' | 'sonnet' | 'opus';

export interface ConcertConfig {
  project_name: string;
  concert_version: string;
}

// === Task Frontmatter (DR-006) ===

export interface TaskFrontmatter {
  task: string;
  title: string;
  phase?: string;
  depends_on: string[];
  wave: number;
  model: ModelTier;
}

// === Managed File Header ===

export const MANAGED_HEADER_PREFIX = 'AUTO-GENERATED BY CONCERT';
export const MANAGED_HEADER_MD = (version: string): string =>
  `<!-- ${MANAGED_HEADER_PREFIX} v${version} \u2014 DO NOT EDIT. This file is managed by Concert and will be overwritten on \`concert update\`. -->`;
export const MANAGED_HEADER_YAML = (version: string): string =>
  `# ${MANAGED_HEADER_PREFIX} v${version} \u2014 DO NOT EDIT. This file is managed by Concert and will be overwritten on \`concert update\`.`;

// === CLAUDE.md Section Markers ===

export const CLAUDE_SECTION_START =
  '<!-- CONCERT:START \u2014 DO NOT MODIFY THIS SECTION. It is managed by Concert and will be overwritten on `concert update`. -->';
export const CLAUDE_SECTION_END = '<!-- CONCERT:END \u2014 DO NOT MODIFY THIS SECTION -->';
